### ISSUE TITLE
TransactionInterceptor be-eindigt transactie alleen op RTEs, en niet checked Exception of Error

### ISSUE THREAD

**Issue by kimholan** [vrijBRP/vrijBRP-Balie#2]
https://github.com/vrijBRP/vrijBRP-Balie/blob/55098a53ea07dd3de0e7d10491b6996485d8e6cf/gba-services/src/main/java/nl/procura/gba/web/services/methodinterception/TransactionInterceptor.java#L42

De broncode lijkt incompleet, er zit wel een property op de zelf ingerichte transactieafhandeling met @Transactional voor 'commitWithException' (mocht dat daarvoor bedoeld zijn), maar de TransactionInterceptor voert geen opschoonactie (close, rollback, commit) uit als het niet expliciet een RTE is, omdat de de commitOrRollback in de try-clause zit.

Bij gebrek aan ondersteuning voor unittests, hieronder een copy/paste met stubs waar de flow zichtbaar is wanneer de service methode een checked exception gooit.  Misschien is het zo bedoeld, maar het is slecht analyseerbaar obv de onvolledige broncode

'Test'-code:
```
import java.lang.annotation.Annotation;
import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;
import java.lang.reflect.AccessibleObject;
import java.lang.reflect.Method;

public class TransactionInterceptorTest {

    private static GbaJpaManager gbaJpaManager = new GbaJpaManager();

    private Method tlMethod;

    public static void main(String[] s) throws Throwable {
        try {
            new TransactionInterceptorTest().invoke(new MethodInvocation() {
                MockService intercepted = new MockService();

                @Override
                public Object proceed() throws Throwable {
                    return getMethod().invoke(intercepted, getArguments());
                }

                @Override
                public Object getThis() {
                    return null;
                }

                @Override
                public AccessibleObject getStaticPart() {
                    return null;
                }

                @Override
                public Object[] getArguments() {
                    return new Object[0];
                }

                @Override
                public Method getMethod() {
                    try {
                        return MockService.class.getMethod("transactional");
                    } catch (NoSuchMethodException e) {
                        throw new AssertionError(e);
                    }
                }
            });
        } finally {
            System.err.println("transactie gestart:" + gbaJpaManager.begin);
            System.err.println("transactie gesloten:" + gbaJpaManager.close);

        }

    }

    protected <T> T getAnnotation(MethodInvocation in, Class<? extends Annotation> cl) {
        return (T) in.getMethod().getAnnotation(cl);
    }

    public Object invoke(MethodInvocation in) throws Throwable {

        beginTransaction(in);
        Object result;

        try {

            result = in.proceed();
            commitOrRollback(in, true);
        } catch (RuntimeException e) {

            commitOrRollback(in, false);
            throw e;
        }

        return result;
    }

    /**
     * Begin een transactie
     */
    private void beginTransaction(MethodInvocation in) {

        Transactional ann = getAnnotation(in, Transactional.class);

        if (ann != null) {

            if (getMethod() == null) {

                setMethod(in.getMethod());

                gbaJpaManager.begin();
            }
        }
    }

    private void commitOrRollback(MethodInvocation in, boolean doCommit) {

        Transactional ann = getAnnotation(in, Transactional.class);

        if (ann != null) {

            if (getMethod() == in.getMethod()) {

                try {
                    gbaJpaManager.close();
                } finally {
                    setMethod(null);
                }
            }
        }
    }

    private Method getMethod() {
        return tlMethod;
    }

    private void setMethod(Method method) {
        tlMethod = method;
    }

    @Target({ElementType.METHOD, ElementType.TYPE})
    @Retention(RetentionPolicy.RUNTIME)
    public @interface Transactional {

        Class[] classes() default Class.class;

        boolean closeAfterCommit() default false;

        boolean commitWithException() default false;

    }

    public interface MethodInvocation
            extends Invocation {

        Method getMethod();

    }

    public interface Invocation
            extends Joinpoint {

        Object[] getArguments();

    }

    public interface Joinpoint {

        Object proceed() throws Throwable;

        Object getThis();

        AccessibleObject getStaticPart();

    }

    static class MockService {

        @Transactional
        public void transactional() throws Exception {
            System.err.println("doe iets");
            throw new Exception("checked exception");
        }

    }

    static class GbaJpaManager {

        private boolean close;

        private boolean begin;

        public void close() {
            close = true;
        }

        public void begin() {
            begin = true;
        }

    }

}
```

Uitvoer is dan zoals hieronder, en de close is nooit aangeroepen. Misschien is het zo bedoeld.
```
doe iets
transactie gestart:true
transactie gesloten:false
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at TransactionInterceptorTest$1.proceed(TransactionInterceptorTest.java:22)
	at TransactionInterceptorTest.invoke(TransactionInterceptorTest.java:68)
	at TransactionInterceptorTest.main(TransactionInterceptorTest.java:17)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.intellij.rt.execution.application.AppMainV2.main(AppMainV2.java:114)
Caused by: java.lang.Exception: checked exception
	at TransactionInterceptorTest$MockService.transactional(TransactionInterceptorTest.java:163)
	... 12 more

```

**Comment by fritsjanssen** [comment]
De entitymanager wordt bijgehouden in https://github.com/vrijBRP/vrijBRP-Balie/blob/main/gba-jpa/src/main/java/nl/procura/gba/jpa/personen/utils/GbaJpaStorage.java in een ThreadLocal gedurende de request.

De filter https://github.com/vrijBRP/vrijBRP-Balie/blob/main/gba-web/src/main/java/nl/procura/gba/web/filters/RequestStorageFilter.java zal de entitymanager na afloop van de request sluiten en eventueel alsnog een rollback doen door de methode GbaJpaStorage.remove() aan te roepen. 

De transactieafhandeling is zeker voor hedendaagse begrippen omslachtig te noemen. De keus voor een eigen oplossing zou vandaag de dag niet meer zo snel gemaakt worden, maar destijds was er eigenlijk alleen JBoss Application Server en dat werd te log en belastend gezien voor de systemen waarop het moest draaien. In dit geval is de flow wat lastig te ontdekken omdat het niet via de code direct te volgen is. 

De broncode is inderdaad nog incompleet. Er ontbreken bij dit project nog een aantal libraries die in de loop van de jaren zijn ontwikkeld. Die komen binnenkort op Github. Dat zijn voornamelijk libraries die je vandaag de dag zou vervangen met Apache commons of spring libraries.
